In [1]:
import numpy as np

In [2]:
a=np.arange(1,13).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
np.sum(a)  #sum of all the elements

78

In [4]:
np.sum(a, axis = 1)  #row wise sum

array([10, 26, 42])

In [6]:
np.sum(a, axis = 0)  #column wise sum

array([15, 18, 21, 24])

In [8]:
np.mean(a)

6.5

In [9]:
a.mean()

6.5

In [10]:
a.min()

1

In [11]:
a.min(axis = 1)

array([1, 5, 9])

In [12]:
a.min(axis = 0)

array([1, 2, 3, 4])

any : np.any tries to find out for atleast one non zero value in the array

In [13]:
a=np.array([True,False,True])
np.any(a)

True

In [14]:
m=np.array([4,3,2,1])
n=np.array([1,2,3,4])
np.any(m<n)

True

In [17]:
# no.all returns true if all the values are non zero
# returns False if atleast one value is zero
a=np.array([True,False,True])
np.all(a)

False

In [18]:
m=np.array([4,3,2,1])
n=np.array([1,2,3,4])
np.all(m<n)

False

In [19]:
m=np.array([4,3,5,6])
n=np.array([1,2,3,4])
np.all(m>n)

True

## Sorting

In [20]:
l=np.array([21,30,1,41,7,52,17])
l

array([21, 30,  1, 41,  7, 52, 17])

In [21]:
np.sort(l)

array([ 1,  7, 17, 21, 30, 41, 52])

In [22]:
np.argsort(l)

array([2, 4, 6, 0, 1, 3, 5], dtype=int64)

In [23]:
np.argmin(l)

2

In [24]:
np.argmax(l)

5

In [30]:
j=np.array([[32,80,12],[3,96,9],[98,75,110]])
j

array([[ 32,  80,  12],
       [  3,  96,   9],
       [ 98,  75, 110]])

In [31]:
np.sort(j)  #default axis 1

array([[ 12,  32,  80],
       [  3,   9,  96],
       [ 75,  98, 110]])

In [32]:
np.sort(j, axis = 1)

array([[ 12,  32,  80],
       [  3,   9,  96],
       [ 75,  98, 110]])

In [33]:
np.sort(j, axis = 0)

array([[  3,  75,   9],
       [ 32,  80,  12],
       [ 98,  96, 110]])

## matrix multiplication

In [34]:
m=np.arange(1,13).reshape((3,4))
n=np.arange(2,14).reshape((3,4))

In [35]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
n

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [37]:
m*n

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [38]:
#method 1
np.matmul(m,n)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [39]:
m=np.arange(1,13).reshape((3,4))
n=np.arange(2,14).reshape((4,3))

In [40]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
n

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [42]:
np.matmul(m,n)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [43]:
#method2
m@n

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [44]:
#method3 (preffered)
np.dot(m,n)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [45]:
a=np.array([1,2,3])
b=np.array([2,3,4])
np.matmul(a,b)

20

In [46]:
np.dot(a,b)

20

In [47]:
np.matmul(4,5)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [49]:
4@5

TypeError: unsupported operand type(s) for @: 'int' and 'int'

In [48]:
np.dot(4,5)

20

In [50]:
m=np.arange(1,10).reshape((3,3))
a=np.array([1,2,3])

In [51]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a

array([1, 2, 3])

In [53]:
m*a

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [54]:
np.dot(m,a)

array([14, 32, 50])

In [56]:
np.dot(a,m)

array([30, 36, 42])

## vectorize

In [58]:
import math
func = np.vectorize(math.log)

In [59]:
a = np.array([1,2,3,4,5])
func(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## Tile

In [60]:
a = np.array([1,2,3,4,5])

In [61]:
a

array([1, 2, 3, 4, 5])

In [62]:
np.tile(a, (2,2))

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])