In [1]:
import numpy as np

## Ravel

In [2]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Flatten returns copy of the array whereas ravel returns view of the array It means if i ravel an array and modify the raveled array, it'll change the original array as well

In [9]:
b = A.flatten()
print(b)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
b[0] = 100
print(b)
print(A)

[100   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
b = A.ravel()
print(b)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
b[0] = 100
print(b)
print(A)

[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## randint()

In [14]:
np.random.randint(5,10)

9

In [15]:
np.random.randint(5,10,2)

array([6, 5])

## rand()

In [16]:
np.random.rand(3)

array([0.71761247, 0.77152379, 0.27058325])

## normal()

In [21]:
s = np.random.normal(100, 2, 10) ## mean = 100, std = 2
s

array([100.88703171,  97.18334515,  96.59604887, 100.49503424,
        98.20304361, 103.895257  , 102.91552766,  98.03019712,
        99.97097389, 100.29001288])

In [19]:
np.mean(s)

100.44043844063795

In [20]:
np.std(s)

1.5959391994691858