In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5]) #create numpy array
a**2  #element wise operation

array([ 1,  4,  9, 16, 25], dtype=int32)

In [5]:
type(a) #type of numpy array

numpy.ndarray

In [6]:
a.dtype  #type of array element

dtype('int32')

In [7]:
m = range(10000)
%timeit [i**2 for i in m]

2 ms ± 57 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
n = np.arange(10000)
%timeit n**2

6.52 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Numpy is fast

In [10]:
# because of one element 4.5 , every element's dtype has been type casted into float
c = np.array([1,2,4.5])
c.dtype

dtype('float64')

In [11]:
# because of one element 4.5 , every element's dtype has been type casted into string
c = np.array([1,2,'4.5'])
c.dtype

dtype('<U11')

In [13]:
# booleans are treated as 1 and 0 for True and False respectively
c = np.array([1,0,True,False])
c

array([1, 0, 1, 0])

In [14]:
b=np.array([1,2,3,4,5])
# used to find out the dimension of the array
b.ndim

1

In [16]:
# used to find out the shape of the numpy array
b.shape

(5,)

In [17]:
# arange function in numpy generates numbers for start to end(excluded) with some step size
# arange( start, stop,step_size)
# arange is different from range --> we can give floats as step size in arange
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [18]:
# linspace is used to create equally spaced numbers between start and end both included.
np.linspace(0,100,25)

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [19]:
m = np.array([[2,3],[4,5]])

In [20]:
m

array([[2, 3],
       [4, 5]])

In [21]:
m.ndim

2

In [22]:
m.shape

(2, 2)

In [23]:
m = np.arange(1,13)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
m.ndim

1

In [26]:
m.shape

(12,)

In [28]:
n = m.reshape(3,4)
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
n.ndim

2

In [30]:
n.shape

(3, 4)

In [32]:
m2=np.arange(1,13)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
# here we knew that we want 3 rows, but not the columns, so we passed -1 as the parameter. 
# numpy will automatically find out the required number of columns it need to display the data.
m2.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
m2.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
m2.reshape(-1, -1) # we need to pass atleast one dimension

ValueError: can only specify one unknown dimension

In [37]:
m2.reshape(5,-1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [38]:
m4=np.array([[1,2,3],[4,5,6,8,0,9]])
m4

array([list([1, 2, 3]), list([4, 5, 6, 8, 0, 9])], dtype=object)

In [40]:
m4=np.arange(1,7)
m5=m4.reshape(2,3)
print(m5)

[[1 2 3]
 [4 5 6]]


In [41]:
m5.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
m6=np.array([1,2,3])
m6

array([1, 2, 3])

In [43]:
m6.shape

(3,)

In [45]:
m6.T   #1d array can not be transformed as it is vector

array([1, 2, 3])

In [46]:
m7=np.arange(1,13).reshape(3,4)
m7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
m7.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# creating special arrays

In [53]:
# creating 1D array with all the values as 0
np.zeros(3) 

array([0., 0., 0.])

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# creating 2D array  of shape (3,) with all the values as 1
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [56]:
m = np.ones((4,4))
m*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [57]:
m = np.ones((4,4), dtype = np.int64)
m*3

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]], dtype=int64)

In [59]:
# creating 2D array with all the values as 4.0
np.full((3,3), 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [60]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1,2,3 and rest as 0
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Indexing

In [63]:
m2 = np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
m2[0][1]

2

In [65]:
m2[0,1]

2

In [66]:
# We can pass a list of indexes of the elements we want to access
m2[[0,1,2],[0,0,0]]

array([1, 5, 9])

## slicing

In [67]:
m2[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
m2[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
m2[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
m2[:,1]

array([ 2,  6, 10])

In [71]:
m2[:,:1]

array([[1],
       [5],
       [9]])

In [72]:
m2[1,::2]

array([5, 7])

## Masking

In [73]:
m1=np.arange(1,13).reshape(3,4)
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
m1<6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [75]:
m1[m1<6]

array([1, 2, 3, 4, 5])

In [76]:
(m1%2 == 0) | (m1%5 == 0)

array([[False,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

### eye vs identity

In [81]:
np.identity(3,5)

TypeError: data type not understood

In [80]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])