In [1]:
import numpy as np

## Concatenate

In [4]:
#1d array
a = np.array([1,2,3])
b = np.array([2,3,4])
np.concatenate([a,b])

array([1, 2, 3, 2, 3, 4])

In [5]:
np.concatenate([a,b], axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [6]:
np.concatenate([a,b], axis=0)

array([1, 2, 3, 2, 3, 4])

In [7]:
#2d array
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,13).reshape(3,4)

In [8]:
np.concatenate([a,b])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np.concatenate([a,b], axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
np.concatenate([a,b], axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [11]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5).reshape((1,4))
print(d)
print("-"*20)
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[1 2 3 4]]


In [12]:
np.concatenate([d,e], axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [13]:
np.concatenate([d,e], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [14]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5)
print(d)
print(d.ndim)
print("-"*30)
print(e)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
------------------------------
[1 2 3 4]
1


In [16]:
np.concatenate([d,e], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [17]:
np.concatenate([d,e], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## Stacking

In [18]:
d=np.arange(1,5)
e=np.arange(1,5)
np.hstack([d,e])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [19]:
np.vstack([d,e])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [20]:
#2d array
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,13).reshape(3,4)
np.hstack([a,b])

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [21]:
np.vstack([a,b])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Splitting

In [22]:
d=np.arange(1,13)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
np.split(d, 3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [24]:
np.split(5)

TypeError: _split_dispatcher() missing 1 required positional argument: 'indices_or_sections'

In [25]:
np.split(13)

TypeError: _split_dispatcher() missing 1 required positional argument: 'indices_or_sections'

In [26]:
np.split(d, [5])

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [27]:
np.split(d, [5,7,12])

[array([1, 2, 3, 4, 5]),
 array([6, 7]),
 array([ 8,  9, 10, 11, 12]),
 array([], dtype=int32)]

In [30]:
np.split(d, [-5, -4])

[array([1, 2, 3, 4, 5, 6, 7]), array([8]), array([ 9, 10, 11, 12])]

In [31]:
d=np.arange(1,13).reshape((1,12))
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
np.split(d, 2, axis=1)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [34]:
np.hsplit(d,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [35]:
np.vsplit(d,2)

ValueError: array split does not result in an equal division

In [36]:
d=np.arange(1,13).reshape((3,4))
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
np.hsplit(d,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [39]:
np.hsplit(d,[1])

[array([[1],
        [5],
        [9]]),
 array([[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]])]

In [40]:
np.vsplit(d,[1])

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

## Broadcasting

In [41]:
b=np.arange(1,7).reshape((3,2))
c=np.arange(1,3)

print(b)
print(b.shape)
print(b.ndim)
print("-"*50)
print(c)
print(c.shape)
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
--------------------------------------------------
[1 2]
(2,)
1


In [42]:
b+c

array([[2, 4],
       [4, 6],
       [6, 8]])

In [43]:
d=np.arange(1,4)
d

array([1, 2, 3])

In [44]:
b+d

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [45]:
a=np.arange(1,7).reshape((3,2))
b=np.array([10,20,30,40]).reshape((2,2))
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]]


In [46]:
a+b

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 